name: Update vuln-list repo
on:
  schedule:
    - cron: "0 0,12 * * *"
  watch:
    types: [started]

jobs:
  update:
    name: Update repo vuln-list
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set Owner
        run: echo "VULNLIST_REPOSITORY_OWNER=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $1}' | sed -e 's/:refs//')" >> $GITHUB_ENV
        shell: bash

      - name: Setup github user email and name
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Compile vuln-list-update
        run: go build -o vuln-list-update .

      - name: NVD
        id: nvd
        run: ./vuln-list-update -target nvd
        continue-on-error: true

      - name: B O G U S   T A R G E T
        id: bogus
        run: ./vuln-list-update -target bogus
        continue-on-error: true

      - name: Alpine Issue Tracker
        id: alpine
        run: ./vuln-list-update -target alpine
        continue-on-error: true

#      - name: Check for failures and Send a message to Microsoft Teams
#        uses: aliencube/microsoft-teams-actions@v0.8.0
#        if: steps.nvd.outputs.status != 'success' || steps.bogus.outputs.status != 'success' || steps.alpine.outputs.status != 'success'
#        with:
#          webhook_uri: ${{ secrets.AQUA_TEAMS_WEBHOOK }}
#          title: <Message Title>
#          summary: vuln-list-update failed
#          text: One or more vendor advisory updates have failed. Check https://github.com/aquasecurity/vuln-list-update/actions?query=is%3Afailure+event%3Aschedule for details.
#          theme_color: EE204D

      - name: Check for failures and Send a message to Microsoft Teams
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        if: steps.nvd.outputs.status != 'success' || steps.bogus.outputs.status != 'success' || steps.alpine.outputs.status != 'success'
        with:
          webhook_url: ${{ secrets.AQUA_TEAMS_WEBHOOK }}
          summary: 'vuln-list-update failed'
          title: 'vuln-list-update'
          text: 'One or more vendor advisory updates have failed. Check link for details.'
          theme-color: 'Error'
          potential-action: |
                  - "@type": "OpenUri"
                    name: "View Failures"
                    targets:
                          - os: "default"
                            uri: "https://github.com/aquasecurity/vuln-list-update/actions?query=is%3Afailure+event%3Aschedule"

      - name: Check for failures and Fail the build
        if: steps.nvd.outputs.status != 'success' || steps.bogus.outputs.status != 'success' || steps.alpine.outputs.status != 'success'
        run: exit 1
