name: Update vuln-list repo
on:
  schedule:
    - cron: "0 0,12 * * *"
  watch:
    types: [started]

jobs:
  update:
    name: Update repo vuln-list
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set Owner
        run: echo "VULNLIST_REPOSITORY_OWNER=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $1}' | sed -e 's/:refs//')" >> $GITHUB_ENV
        shell: bash

      - name: Setup github user email and name
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Compile vuln-list-update
        run: go build -o vuln-list-update .

      - name: NVD
        id: nvd
        run: ./vuln-list-update -target nvd
        continue-on-error: true

      - name: B O G U S   T A R G E T
        id: bogus
        run: ./vuln-list-update -target bogus
        continue-on-error: true

      - name: Alpine Issue Tracker
        id: alpine
        run: ./vuln-list-update -target alpine
        continue-on-error: true

      - name: Check on failures
        if: steps.nvd.outputs.status != 'success' || steps.bogus.outputs.status != 'success' || steps.alpine.outputs.status != 'success'
        run: exit 1

